<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="autofixture" Version="4.18.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="nunit3testadapter" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DoggyFrictions.ExternalApi\DoggyFrictions.ExternalApi.csproj" />
  </ItemGroup>

</Project>
