version: "3.9"
services:
  tests:
    build:
      context: .
      target: build
    command: >-
      dotnet test --no-build --nologo --blame-hang --blame-hang-timeout 60s --logger:"console;verbosity=detailed"
