version: "3.9"
services:
  tests:
    build:
      context: .
      target: copy-all
    command: >-
      dotnet test --nologo --blame-hang --blame-hang-timeout 60s --logger:"console;verbosity=detailed"
